FROM node:18.16.0-slim

WORKDIR /usr/src/app
COPY index.js package.json /usr/src/app/

RUN apt update && apt install bash && npm config set script-shell=bash

CMD ["npm", "run", "start"]
# CMD ["node", "index.js"]
